services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: rando_user
      POSTGRES_PASSWORD: rando_password
      POSTGRES_DB: rando_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
